site_name: Aiming Module Documentation
docs_dir: 'src'
site_dir: 'docs'
nav:
  - Home: ./index.md
  - Examples:
    - Index: ./Examples/index.md
    - Namecall: ./Examples/namecall.md
  - API Reference:
    - Settings:
      - Enabled: ./APIReference/Settings/Enabled.md
      - FOV: ./APIReference/Settings/FOV.md
      - FOV Colour: ./APIReference/Settings/FOVColour.md
      - FOV Sides: ./APIReference/Settings/FOVSides.md
      - Hit Chance: ./APIReference/Settings/HitChance.md
      - Raycast Ignore: ./APIReference/Settings/RaycastIgnore.md
      - Show FOV: ./APIReference/Settings/ShowFOV.md
      - Target Part: ./APIReference/Settings/TargetPart.md
      - Visible Check: ./APIReference/Settings/VisibleCheck.md
    - Ignoring:
      - Players: ./APIReference/Ignoring/Players.md
      - Teams: ./APIReference/Ignoring/Teams.md
    - Beizer Curve:
      - Index: ./APIReference/BeizerCurve/index.md
      - AimTo: ./APIReference/BeizerCurve/AimTo.md

theme:
  name: material
markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences